# Generated by Django 6.0.1 on 2026-01-20 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField()),
                ('grade', models.CharField(max_length=2)),
                ('approved', models.BooleanField(default=False)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academics.enrollment')),
            ],
        ),
    ]
